// Code generated by go-swagger; DO NOT EDIT.

package restapi

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
)

var (
	// SwaggerJSON embedded version of the swagger document used at generation time
	SwaggerJSON json.RawMessage
	// FlatSwaggerJSON embedded flattened version of the swagger document used at generation time
	FlatSwaggerJSON json.RawMessage
)

func init() {
	SwaggerJSON = json.RawMessage([]byte(`{
  "consumes": [
    "application/json"
  ],
  "produces": [
    "application/json"
  ],
  "schemes": [
    "http"
  ],
  "swagger": "2.0",
  "info": {
    "description": "Maintaining users database for bookstore_users-api",
    "title": "A Book Store users api",
    "version": "1.0.0"
  },
  "paths": {
    "/users/{user_id}": {
      "get": {
        "tags": [
          "get user by id"
        ],
        "operationId": "getUserById",
        "parameters": [
          {
            "type": "integer",
            "description": "id of the user",
            "name": "user_id",
            "in": "path",
            "required": true
          }
        ],
        "responses": {
          "200": {
            "description": "user fetched successfully",
            "schema": {
              "$ref": "#/definitions/User"
            }
          },
          "default": {
            "description": "error response",
            "schema": {
              "$ref": "#/definitions/RestErr"
            }
          }
        }
      }
    }
  },
  "definitions": {
    "RestErr": {
      "type": "object",
      "required": [
        "message"
      ],
      "properties": {
        "code": {
          "type": "string",
          "minLength": 1
        },
        "message": {
          "type": "string",
          "minLength": 1
        },
        "status": {
          "type": "string",
          "minLength": 1
        }
      }
    },
    "User": {
      "type": "object",
      "required": [
        "first_name",
        "last_name",
        "email"
      ],
      "properties": {
        "date_created": {
          "type": "string",
          "minLength": 1,
          "readOnly": true
        },
        "email": {
          "type": "string",
          "minLength": 1
        },
        "first_name": {
          "type": "string",
          "minLength": 1
        },
        "id": {
          "type": "integer",
          "format": "int64",
          "readOnly": true
        },
        "last_name": {
          "type": "string",
          "minLength": 1
        }
      }
    }
  }
}`))
	FlatSwaggerJSON = json.RawMessage([]byte(`{
  "consumes": [
    "application/json"
  ],
  "produces": [
    "application/json"
  ],
  "schemes": [
    "http"
  ],
  "swagger": "2.0",
  "info": {
    "description": "Maintaining users database for bookstore_users-api",
    "title": "A Book Store users api",
    "version": "1.0.0"
  },
  "paths": {
    "/users/{user_id}": {
      "get": {
        "tags": [
          "get user by id"
        ],
        "operationId": "getUserById",
        "parameters": [
          {
            "type": "integer",
            "description": "id of the user",
            "name": "user_id",
            "in": "path",
            "required": true
          }
        ],
        "responses": {
          "200": {
            "description": "user fetched successfully",
            "schema": {
              "$ref": "#/definitions/User"
            }
          },
          "default": {
            "description": "error response",
            "schema": {
              "$ref": "#/definitions/RestErr"
            }
          }
        }
      }
    }
  },
  "definitions": {
    "RestErr": {
      "type": "object",
      "required": [
        "message"
      ],
      "properties": {
        "code": {
          "type": "string",
          "minLength": 1
        },
        "message": {
          "type": "string",
          "minLength": 1
        },
        "status": {
          "type": "string",
          "minLength": 1
        }
      }
    },
    "User": {
      "type": "object",
      "required": [
        "first_name",
        "last_name",
        "email"
      ],
      "properties": {
        "date_created": {
          "type": "string",
          "minLength": 1,
          "readOnly": true
        },
        "email": {
          "type": "string",
          "minLength": 1
        },
        "first_name": {
          "type": "string",
          "minLength": 1
        },
        "id": {
          "type": "integer",
          "format": "int64",
          "readOnly": true
        },
        "last_name": {
          "type": "string",
          "minLength": 1
        }
      }
    }
  }
}`))
}
